export const adjectives = [
    "additional",
    "afraid",
    "angry",
    "anxious",
    "asleep",
    "attentive",
    "available",
    "basic",
    "beautiful",
    "big",
    "boring",
    "brave",
    "bright",
    "busy",
    "calm",
    "careful",
    "cheap",
    "clean",
    "clever",
    "cold",
    "comfortable",
    "confident",
    "conscious",
    "constant",
    "convenient",
    "cool",
    "correct",
    "curious",
    "dangerous",
    "dark",
    "deep",
    "different",
    "difficult",
    "dirty",
    "easy",
    "efficient",
    "empty",
    "every",
    "exact",
    "exciting",
    "expensive",
    "fair",
    "famous",
    "fast",
    "fat",
    "fine",
    "firm",
    "flat",
    "foreign",
    "formal",
    "former",
    "free",
    "fresh",
    "friendly",
    "frightful",
    "full",
    "funny",
    "gorgeous",
    "guilty",
    "happy",
    "hard",
    "healthy",
    "heavy",
    "helpful",
    "historical",
    "honest",
    "hot",
    "huge",
    "hungry",
    "ill",
    "illegal",
    "important",
    "impossible",
    "independent",
    "informal",
    "innocent",
    "interesting",
    "international",
    "kind",
    "large",
    "leading",
    "legal",
    "light",
    "little",
    "lonely",
    "long",
    "loose",
    "loud",
    "lucky",
    "necessary",
    "nice",
    "normal",
    "obvious",
    "official",
    "old",
    "opposite",
    "perfect",
    "pleasant",
    "polite",
    "poor",
    "popular",
    "possible",
    "powerful",
    "quiet",
    "rare",
    "recent",
    "relevant",
    "remarkable",
    "remote",
    "responsible",
    "rich",
    "rude",
    "sad",
    "safe",
    "secure",
    "sensible",
    "short",
    "silly",
    "similar",
    "slow",
    "small",
    "smooth",
    "strange",
    "strict",
    "strong",
    "successful",
    "sudden",
    "suitable",
    "suspicious",
    "sweet",
    "tall",
    "tasty",
    "terrible",
    "thin",
    "thirsty",
    "tight",
    "tiny",
    "tired",
    "traditional",
    "typical",
    "useful",
    "usual",
    "valuable",
    "warm",
    "weak",
    "weird",
    "wide",
    "wise",
    "wonderful",
    "young"
    ];
export const nouns = [
    "action",
    "activity",
    "age",
    "air",
    "animal",
    "area",
    "authority",
    "bank",
    "body",
    "book",
    "building",
    "business",
    "car",
    "case",
    "centre",
    "century",
    "change",
    "child",
    "city",
    "community",
    "company",
    "condition",
    "control",
    "country",
    "course",
    "court",
    "day",
    "decision",
    "development",
    "door",
    "education",
    "effect",
    "end",
    "example",
    "experience",
    "eye",
    "face",
    "fact",
    "family",
    "father",
    "field",
    "figure",
    "flat",
    "food",
    "form",
    "friend",
    "game",
    "girl",
    "government",
    "group",
    "guy",
    "hand",
    "head",
    "health",
    "history",
    "home",
    "hour",
    "house",
    "idea",
    "industry",
    "information",
    "interest",
    "job",
    "kid",
    "language",
    "law",
    "level",
    "life",
    "line",
    "love",
    "man",
    "manager",
    "manner",
    "market",
    "million",
    "mind",
    "minute",
    "moment",
    "money",
    "month",
    "morning",
    "mother",
    "name",
    "need",
    "night",
    "number",
    "office",
    "opportunity",
    "order",
    "paper",
    "parent",
    "part",
    "party",
    "people",
    "period",
    "person",
    "place",
    "plan",
    "point",
    "police",
    "policy",
    "position",
    "power",
    "president",
    "price",
    "problem",
    "process",
    "program",
    "project",
    "quality",
    "question",
    "reason",
    "relationship",
    "report",
    "research",
    "rest",
    "result",
    "road",
    "room",
    "school",
    "sense",
    "service",
    "side",
    "society",
    "staff",
    "story",
    "street",
    "student",
    "study",
    "support",
    "system",
    "table",
    "teacher",
    "team",
    "term",
    "thing",
    "time",
    "type",
    "use",
    "view",
    "war",
    "water",
    "way",
    "week",
    "woman",
    "word",
    "work",
    "world",
    "year"
    ];
export const verbs = [
    "is",
    "has",
    "does",
    "says",
    "gets",
    "finds",
    "tells about",
    "asks for",
    "uses",
    "comes to",
    "knows about",
    "goes to",
    "makes",
    "gives",
    "wants",
    "looks like",
    "thinks about",
    "takes",
    "sees",
    "works on",
    "tries",
    "leaves for",
    "needs",
    "seems to be",
    "becomes",
    "calls",
    "feels",
    "puts",
    "keeps",
    "helps",
    "spends",
    "begins",
    "walks through",
    "closes",
    "means",
    "believes in",
    "plays",
    "reminds of",
    "includes",
    "sets",
    "hears",
    "changes",
    "moves to",
    "creates",
    "appears at",
    "opens",
    "stands next to",
    "serves as",
    "runs from",
    "remembers",
    "buys",
    "brings",
    "wins",
    "learns",
    "lives in",
    "continues",
    "meets",
    "shows",
    "allows",
    "writes",
    "loses",
    "offers",
    "sits next to",
    "prohibits",
    "reads about",
    "follows",
    "teaches",
    "pays for",
    "speaks about",
    "stops",
    "watches",
    "develops",
    "falls to",
    "passes",
    "produces",
    "carries",
    "supports",
    "thanks",
    "provides",
    "raises",
    "adds",
    "agrees with",
    "understands",
    "receives",
    "jumps into",
    "chooses",
    "hopes for",
    "draws",
    "decides to",
    "breaks",
    "sends",
    "builds",
    "eats",
    "hits",
    "dies because of",
    "catches",
    "swims in",
    "sells",
    "returns to",
    "kills",
    "explains",
    "stays at",
    "cuts",
    "solves",
    "loves",
    "discusses",
    "achieves",
    "avoids",
    "prepares for",
    "forgets about",
    "suggests",
    "depends on",
    "translates",
    "approves",
    "cooks",
    "studies",
    "answers",
    "smiles because of",
    "repeats",
    "joins",
    "ends",
    "orders",
    "plans",
    "dances with",
    "starts",
    "finishes",
    "wears",
    "rides",
    "cancels",
    "lies on",
    "cries because of",
    "drinks",
    "visits",
    "drives",
    "wishes",
    "sings about",
    "responds to",
    "flies from",
    "holds",
    "talks to",
    "is afraid of",
    "screams because of",
    "turns into",
    "searches for",
    "listens to",
    "connects to",
    "travels to"
    ];
export const names = [
    "Alexander",
    "Dmitry",
    "Maxim",
    "Sergey",
    "Andrey",
    "Alexey",
    "Artyom",
    "Ilya",
    "Kirill",
    "Mikhail",
    "Nikita",
    "Matvey",
    "Roman",
    "Egor",
    "Arseny",
    "Ivan",
    "Denis",
    "Evgeny",
    "Daniil",
    "Timofey",
    "Vladislav",
    "Igor",
    "Vladimir",
    "Pavel",
    "Ruslan",
    "Mark",
    "Konstantin",
    "Timur",
    "Oleg",
    "Yaroslav",
    "Anton",
    "Nikolay",
    "Gleb",
    "Danil",
    "Savely",
    "Vadim",
    "Stepan",
    "Yury",
    "Bogdan",
    "Artur",
    "Semyon",
    "Makar",
    "Lev",
    "Viktor",
    "Elisey",
    "Vitaly",
    "Vyacheslav",
    "Zahar",
    "Miron",
    "Damir",
    "Georgy",
    "David",
    "Platon",
    "Anatoly",
    "Grigory",
    "Demid",
    "Danila",
    "Stanislav",
    "Vasily",
    "Fyodor",
    "Rodion",
    "Leonid",
    "Danis",
    "Valery",
    "Svyatoslav",
    "Boris",
    "Eduard",
    "Marat",
    "German",
    "Daniel",
    "Petr",
    "Amir",
    "Vsevolod",
    "Miroslav",
    "Gordey",
    "Artemy",
    "Emil",
    "Nazar",
    "Savva",
    "Yan",
    "Rustam",
    "Ignat",
    "Vlad",
    "Albert",
    "Tamerlan",
    "Aydar",
    "Robert",
    "Adel",
    "Marsel",
    "Ildar",
    "Samir",
    "Tihon",
    "Ramil",
    "Rinat",
    "Radmir",
    "Philip",
    "Arsen",
    "Rostislav",
    "Svyatogor",
    "Yaromir"
    ];
export const languages = ["En", "Ru"];
export const chars = "0123456789abcdefghijklmnopqrstuvwxyz!@#$%^&*()ABCDEFGHIJKLMNOPQRSTUVWXYZ";